services:
  db:
    image: postgis/postgis:16-3.4
    container_name: tfg_postgis_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tfgpassword
      POSTGRES_DB: incendios_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
